# Generated by Django 2.0.7 on 2020-05-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thuvienbk', '0002_auto_20200506_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_pdf', models.FileField(upload_to='ebooks/')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thuvienbk.Book')),
            ],
        ),
    ]
